version: "3.8"
services:
  whisper:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/python-docker
      - whisper-volume:/whisper-volume
    environment:
      FLASK_ENV: development

volumes:
    whisper-volume:
      external: true


